name: CI
on: [push, pull_request]

jobs:
  install:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # This can be removed once RALib is available from a maven repository.
      - name: Install RALib manually
        run: |
          git clone "https://github.com/LearnLib/ralib"
          cd ralib
          git checkout 2b6817ed7e532f0aecbd47907d3dc0de4fdf94e0
          mvn install -DskipTests

      - name: Spotless check, Spotbugs check and Install
        run: mvn install
